### ISSUE TITLE
Crash when loading with SQLite

### ISSUE THREAD

**Issue by yitzy299** [fabricservertools/DeltaLogger#2]
`---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 04/01/2021, 10:12
Description: Watching Server

java.lang.Error: Watchdog
	at net.minecraft.server.dedicated.DedicatedServerWatchdog.run(DedicatedServerWatchdog.java:43)
	at java.base/java.lang.Thread.run(Thread.java:834)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Thread Dump --
Details:
	Threads: "Reference Handler" daemon prio=10 Id=2 RUNNABLE
	at java.base@11.0.9.1/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
	at java.base@11.0.9.1/java.lang.ref.Reference.processPendingReferences(Reference.java:241)
	at java.base@11.0.9.1/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:213)

"Finalizer" daemon prio=8 Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@3450d1ce
	at java.base@11.0.9.1/java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@3450d1ce
	at java.base@11.0.9.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
	at java.base@11.0.9.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
	at java.base@11.0.9.1/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:170)

"Signal Dispatcher" daemon prio=9 Id=4 RUNNABLE

"Attach Listener" daemon prio=5 Id=5 RUNNABLE

"JDWP Transport Listener: dt_socket" daemon prio=10 Id=11 RUNNABLE

"JDWP Event Helper Thread" daemon prio=10 Id=12 RUNNABLE

"JDWP Command Reader" daemon prio=10 Id=13 RUNNABLE

"Common-Cleaner" daemon prio=8 Id=15 TIMED_WAITING on java.lang.ref.ReferenceQueue$Lock@3a973934
	at java.base@11.0.9.1/java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@3a973934
	at java.base@11.0.9.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
	at java.base@11.0.9.1/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:148)
	at java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)
	at java.base@11.0.9.1/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:134)

"Worker-Bootstrap-2" daemon prio=5 Id=29 WAITING on java.util.concurrent.ForkJoinPool@3ea8babe
	at java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.ForkJoinPool@3ea8babe
	at java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.9.1/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
	at java.base@11.0.9.1/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"Worker-Bootstrap-3" daemon prio=5 Id=30 WAITING on java.util.concurrent.ForkJoinPool@3ea8babe
	at java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.ForkJoinPool@3ea8babe
	at java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.9.1/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
	at java.base@11.0.9.1/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"Worker-Bootstrap-4" daemon prio=5 Id=31 WAITING on java.util.concurrent.ForkJoinPool@3ea8babe
	at java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.ForkJoinPool@3ea8babe
	at java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.9.1/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
	at java.base@11.0.9.1/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"Worker-Bootstrap-5" daemon prio=5 Id=32 WAITING on java.util.concurrent.ForkJoinPool@3ea8babe
	at java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.ForkJoinPool@3ea8babe
	at java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.9.1/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
	at java.base@11.0.9.1/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"Worker-Bootstrap-6" daemon prio=5 Id=33 TIMED_WAITING on java.util.concurrent.ForkJoinPool@3ea8babe
	at java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.ForkJoinPool@3ea8babe
	at java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.parkUntil(LockSupport.java:275)
	at java.base@11.0.9.1/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1619)
	at java.base@11.0.9.1/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"Worker-Bootstrap-7" daemon prio=5 Id=34 WAITING on java.util.concurrent.ForkJoinPool@3ea8babe
	at java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.ForkJoinPool@3ea8babe
	at java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.9.1/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
	at java.base@11.0.9.1/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"Timer hack thread" daemon prio=5 Id=35 TIMED_WAITING
	at java.base@11.0.9.1/java.lang.Thread.sleep(Native Method)
	at net.minecraft.util.Util$6.run(Util.java:519)

"Worker-Main-8" daemon prio=5 Id=36 WAITING on java.util.concurrent.ForkJoinPool@7baa330f
	at java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.ForkJoinPool@7baa330f
	at java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.9.1/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
	at java.base@11.0.9.1/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"Worker-Main-9" daemon prio=5 Id=37 WAITING on java.util.concurrent.ForkJoinPool@7baa330f
	at java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.ForkJoinPool@7baa330f
	at java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.9.1/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
	at java.base@11.0.9.1/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"Worker-Main-10" daemon prio=5 Id=38 WAITING on java.util.concurrent.ForkJoinPool@7baa330f
	at java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.ForkJoinPool@7baa330f
	at java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.9.1/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
	at java.base@11.0.9.1/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"Worker-Main-12" daemon prio=5 Id=40 WAITING on java.util.concurrent.ForkJoinPool@7baa330f
	at java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.ForkJoinPool@7baa330f
	at java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.9.1/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
	at java.base@11.0.9.1/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"Worker-Main-13" daemon prio=5 Id=41 WAITING on java.util.concurrent.ForkJoinPool@7baa330f
	at java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.ForkJoinPool@7baa330f
	at java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.9.1/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
	at java.base@11.0.9.1/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"Worker-Main-14" daemon prio=5 Id=42 TIMED_WAITING on java.util.concurrent.ForkJoinPool@7baa330f
	at java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.ForkJoinPool@7baa330f
	at java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.parkUntil(LockSupport.java:275)
	at java.base@11.0.9.1/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1619)
	at java.base@11.0.9.1/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"Snooper Timer" daemon prio=5 Id=44 WAITING on java.util.TaskQueue@49464315
	at java.base@11.0.9.1/java.lang.Object.wait(Native Method)
	-  waiting on java.util.TaskQueue@49464315
	at java.base@11.0.9.1/java.lang.Object.wait(Object.java:328)
	at java.base@11.0.9.1/java.util.TimerThread.mainLoop(Timer.java:527)
	at java.base@11.0.9.1/java.util.TimerThread.run(Timer.java:506)

"Java2D Disposer" daemon prio=10 Id=45 WAITING on java.lang.ref.ReferenceQueue$Lock@4a9b8d90
	at java.base@11.0.9.1/java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@4a9b8d90
	at java.base@11.0.9.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
	at java.base@11.0.9.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
	at java.desktop@11.0.9.1/sun.java2d.Disposer.run(Disposer.java:144)
	at java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)

"AWT-Windows" daemon prio=6 Id=47 RUNNABLE (in native)
	at java.desktop@11.0.9.1/sun.awt.windows.WToolkit.eventLoop(Native Method)
	at java.desktop@11.0.9.1/sun.awt.windows.WToolkit.run(WToolkit.java:305)
	at java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)

"TimerQueue" daemon prio=5 Id=51 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@1b85cc40
	at java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@1b85cc40
	at java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.9.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
	at java.base@11.0.9.1/java.util.concurrent.DelayQueue.take(DelayQueue.java:217)
	at java.desktop@11.0.9.1/javax.swing.TimerQueue.run(TimerQueue.java:171)
	at java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)

	Number of locked synchronizers = 1
	- java.util.concurrent.locks.ReentrantLock$NonfairSync@319da337

"Thread-1" daemon prio=5 Id=50 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@60a06ace
	at java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@60a06ace
	at java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.9.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
	at java.base@11.0.9.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
	at app//com.mojang.util.QueueLogAppender.getNextLogEvent(QueueLogAppender.java:77)
	at net.minecraft.server.dedicated.gui.DedicatedServerGui.method_13972(DedicatedServerGui.java:130)
	at net.minecraft.server.dedicated.gui.DedicatedServerGui$$Lambda$3617/0x0000000100a5ec40.run(Unknown Source)
	at java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)

"DestroyJavaVM" prio=5 Id=55 RUNNABLE

"Server console handler" daemon prio=5 Id=54 RUNNABLE (in native)
	at java.base@11.0.9.1/java.io.FileInputStream.readBytes(Native Method)
	at java.base@11.0.9.1/java.io.FileInputStream.read(FileInputStream.java:279)
	at java.base@11.0.9.1/java.io.BufferedInputStream.read1(BufferedInputStream.java:290)
	at java.base@11.0.9.1/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
	-  locked java.io.BufferedInputStream@76418c47
	at java.base@11.0.9.1/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at java.base@11.0.9.1/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at java.base@11.0.9.1/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	-  locked java.io.InputStreamReader@2a990da3
	at java.base@11.0.9.1/java.io.InputStreamReader.read(InputStreamReader.java:185)
	...

"ObjectCleanerThread" daemon prio=1 Id=56 TIMED_WAITING on java.lang.ref.ReferenceQueue$Lock@1fcb337c
	at java.base@11.0.9.1/java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@1fcb337c
	at java.base@11.0.9.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
	at app//io.netty.util.internal.ObjectCleaner$1.run(ObjectCleaner.java:54)
	at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)

"Netty Server IO #0" daemon prio=5 Id=57 RUNNABLE
	at java.base@11.0.9.1/sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
	at java.base@11.0.9.1/sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:357)
	at java.base@11.0.9.1/sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:182)
	at java.base@11.0.9.1/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:124)
	-  locked sun.nio.ch.Util$2@7cdedc51
	-  locked sun.nio.ch.WindowsSelectorImpl@6075439
	at java.base@11.0.9.1/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:136)
	at app//io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:756)
	at app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:411)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	...

"IO-Worker-15" prio=5 Id=58 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@6491b54f
	at java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@6491b54f
	at java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
	at java.base@11.0.9.1/java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:462)
	at java.base@11.0.9.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:361)
	at java.base@11.0.9.1/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:937)
	at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1053)
	at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
	at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	...

"IO-Worker-17" prio=5 Id=60 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@6491b54f
	at java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@6491b54f
	at java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
	at java.base@11.0.9.1/java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:462)
	at java.base@11.0.9.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:361)
	at java.base@11.0.9.1/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:937)
	at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1053)
	at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
	at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	...

"Server Watchdog" daemon prio=5 Id=61 RUNNABLE
	at java.management@11.0.9.1/sun.management.ThreadImpl.dumpThreads0(Native Method)
	at java.management@11.0.9.1/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:521)
	at java.management@11.0.9.1/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:509)
	at net.minecraft.server.dedicated.DedicatedServerWatchdog.run(DedicatedServerWatchdog.java:41)
	at java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)

"mysql-cj-abandoned-connection-cleanup" daemon prio=5 Id=62 TIMED_WAITING on java.lang.ref.ReferenceQueue$Lock@22873a72
	at java.base@11.0.9.1/java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@22873a72
	at java.base@11.0.9.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
	at app//com.mysql.cj.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:85)
	at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)

	Number of locked synchronizers = 1
	- java.util.concurrent.ThreadPoolExecutor$Worker@65c2399a

"HikariPool-1 housekeeper" daemon prio=5 Id=63 TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@28b15627
	at java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@28b15627
	at java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
	at java.base@11.0.9.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123)
	at java.base@11.0.9.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
	at java.base@11.0.9.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
	at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
	at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
	at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	...

"AWT-Shutdown" prio=5 Id=66 WAITING on java.lang.Object@142b6994
	at java.base@11.0.9.1/java.lang.Object.wait(Native Method)
	-  waiting on java.lang.Object@142b6994
	at java.base@11.0.9.1/java.lang.Object.wait(Object.java:328)
	at java.desktop@11.0.9.1/sun.awt.AWTAutoShutdown.run(AWTAutoShutdown.java:291)
	at java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)

"AWT-EventQueue-0" prio=6 Id=65 RUNNABLE

-- Performance stats --
Details:
	Random tick rate: 3
	Level stats: ResourceKey[minecraft:dimension / minecraft:overworld]: players: 0, entities: 79 [minecraft:pig:28,minecraft:cow:24,minecraft:sheep:16,minecraft:chicken:10,minecraft:donkey:1], block_entities: 3 [minecraft:mob_spawner:1,minecraft:beehive:1,minecraft:chest:1], block_ticks: 159844, fluid_ticks: 165, chunk_source: ServerChunkCache: 2025,
ResourceKey[minecraft:dimension / minecraft:the_nether]: players: 0, entities: 0 [], block_entities: 0 [], block_ticks: 0, fluid_ticks: 0, chunk_source: ServerChunkCache: 0,
ResourceKey[minecraft:dimension / minecraft:the_end]: players: 0, entities: 0 [], block_entities: 0 [], block_ticks: 0, fluid_ticks: 0, chunk_source: ServerChunkCache: 0
Stacktrace:
	at net.minecraft.server.dedicated.DedicatedServerWatchdog.run(DedicatedServerWatchdog.java:43)
	at java.base/java.lang.Thread.run(Thread.java:834)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 11.0.9.1, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
	Memory: 486695440 bytes (464 MB) / 1630535680 bytes (1555 MB) up to 2088763392 bytes (1992 MB)
	CPUs: 8
	JVM Flags: 3 total; -Xdebug -Xnoagent -Xrunjdwp:transport=dt_socket,address=localhost:52114,server=n,suspend=y
	Fabric Mods: 
		deltalogger: DeltaLogger ${version}
		fabric: Fabric API 0.26.3+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+6a2618f53a
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+6a2618f53a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+6a2618f53a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+6a2618f53a
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+6a2618f53a
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+6a2618f53a
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+6a2618f53a
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+6a2618f53a
		fabric-networking-v0: Fabric Networking (v0) 0.3.1+2a4333d33a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
		fabric-particles-v1: fabric-particles-v1 0.2.2+6a2618f53a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.1+285766753a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.0+552549d53a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.1+f1d8af063a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
		fabricloader: Fabric Loader 0.10.8
		minecraft: Minecraft 1.16.4
	Player Count: 0 / 20; []
	Data Packs: vanilla, Fabric Mods
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)`
	@unsupervisednn

**Comment by ElijahRus250** [comment]
I am getting this issue and It is constantly crashing my server. Can confirm

**Comment by unsupervisednn** [comment]
@yitzy299 I don't see the exception but is this fixed with latest commit?

**Comment by unsupervisednn** [comment]
@ElijahRus250 please don't use it on a live server yet as things are still changing a lot, I've added a disclaimer to the Readme.

**Comment by yitzy299** [comment]
Yep, it works

**Comment by yitzy299** [comment]
Fixed in latest commit
