### ISSUE TITLE
Broken on build

### ISSUE THREAD

**Issue by yitzy299** [fabricservertools/DeltaLogger#5]
```[18:42:00] [main/FATAL] (Minecraft) Failed to start the minecraft server
--
  | java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'deltalogger'!
  | at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.7) ~[?:?]
  | at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53) ~[fabric-server-launch.jar:?]
  | at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric-server-launch.jar:?]
  | at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) ~[fabric-server-launch.jar:?]
  | at net.minecraft.server.Main.main(Main:92) [intermediary-server.jar:?]
  | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
  | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
  | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
  | at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
  | at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-server-launch.jar:?]
  | at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139) [fabric-server-launch.jar:?]
  | at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:27) [fabric-server-launch.jar:?]
  | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
  | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
  | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
  | at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
  | at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabric-server-launch.jar:?]
  | at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabric-server-launch.jar:?]
  | at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabric-server-launch.jar:?]
  | Caused by: java.lang.NoClassDefFoundError: com/github/fabricservertools/deltalogger/shadow/com/google/common/io/MoreFiles
  | at com.github.fabricservertools.deltalogger.ModInit.loadConfig(ModInit.java:45) ~[deltalogger-1.16.4-1.0.0.jar:?]
  | at com.github.fabricservertools.deltalogger.ModInit.onModInit(ModInit.java:63) ~[deltalogger-1.16.4-1.0.0.jar:?]
  | at com.github.fabricservertools.deltalogger.ModInit.onInitialize(ModInit.java:116) ~[deltalogger-1.16.4-1.0.0.jar:?]
  | at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
  | ... 17 more
  | Caused by: java.lang.ClassNotFoundException: com.github.fabricservertools.deltalogger.shadow.com.google.common.io.MoreFiles
  | at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606) ~[?:?]
  | at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168) ~[?:?]
  | at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
  | at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:56) ~[fabric-server-launch.jar:?]
  | at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
  | at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168) ~[fabric-server-launch.jar:?]
  | at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
  | at com.github.fabricservertools.deltalogger.ModInit.loadConfig(ModInit.java:45) ~[deltalogger-1.16.4-1.0.0.jar:?]
  | at com.github.fabricservertools.deltalogger.ModInit.onModInit(ModInit.java:63) ~[deltalogger-1.16.4-1.0.0.jar:?]
  | at com.github.fabricservertools.deltalogger.ModInit.onInitialize(ModInit.java:116) ~[deltalogger-1.16.4-1.0.0.jar:?]
  | at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
  | ... 17 more
```

**Comment by unsupervisednn** [comment]
Try now

**Comment by yitzy299** [comment]
Still no

**Comment by yitzy299** [comment]
I think I've fixed it, I'll close once I've committed the fix
